apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: canal
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: canal
  template:
    spec:
      containers:
      - name: kube-flannel
        env:
        - name: FLANNELD_IFACE_REGEX_TIRORI
          value: ^10\.0\.
