kind: DaemonSet
metadata:
  name: canal
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: kube-flannel
        env:
        - name: FLANNELD_IFACE_REGEX
          value: ^10\.0\.
